back/.eslintrc.js
back/.gitignore
back/.prettierrc
back/nest-cli.json
back/package-lock.json
back/package.json
back/src/app.controller.spec.ts
back/src/app.controller.ts
back/src/app.module.ts
back/src/app.service.ts
back/src/main.ts
back/src/modules/auth/auth.controller.ts
back/src/modules/auth/auth.module.ts
back/src/modules/auth/google-auth.service.ts
back/test/app.e2e-spec.ts
back/test/jest-e2e.json
back/tsconfig.build.json
back/tsconfig.json

- prettier 통일
- nestjs 세팅
- 환경변수 설정
- Oauth2.0 google 인증 키 발급 및 로직 구현
To Do
- 네이버, 카카오 Oauth 구현
- 토큰 방식으로 변경
- 디렉토리 및 모듈 구조 설계

[송현우] NestJS 초기 세팅

---

back/package-lock.json
back/package.json
back/src/modules/auth/auth.controller.ts
back/src/modules/auth/auth.module.ts
back/src/modules/auth/google-auth.strategy.ts
back/src/modules/auth/kakao-auth.strategy.ts
back/src/modules/auth/naver-auth.strategy.ts

[송현우] Oauth2.0 AuthStrategy 설계

---

.github/workflows/FrontEnd.yml

front 디렉터리 내부에서 npm 을 실행하지 않아 fix

fix: git action npm bug

---

back/package-lock.json
back/package.json
back/src/app.module.ts
back/src/config/ormconfig.ts
back/src/main.ts
back/src/modules/message/entity/message.entity.ts
back/src/modules/message/message.controller.ts
back/src/modules/message/message.module.ts
back/src/modules/message/message.service.ts
back/tsconfig.json

debugging
1. ormconfig.json이 인식되지 않는 오류 -> process.env 사용하도록 수정
2. process.env이 ormconfig.ts에서만 undefined로 뜨는 오류 -> dotenv.config 위치를 ormconfig.ts에서 하도록 수정
3. ER_NOT_SUPPORTED_AUTH_MODE 에러 -> npm un mysql && npm i mysql2
</div>

[송현우] typeORM 설정

---

front/src/components/SnowGlobeCanvas/GiftBox.tsx
front/src/components/SnowGlobeCanvas/Raycaster.tsx
front/src/components/SnowGlobeCanvas/Snow.tsx
front/src/components/SnowGlobeCanvas/SnowGlobeCanvas.tsx

closed #34 
이벤트 등록 분기를 나누어 snowball 의 클릭 (터치) 시간차를 활용해 줌과 드래그를 구분하였습니다.

[김찬우, 오승엽, 서민아] snowball 줌 기능 구현

---

front/src/components/SnowGlobeCanvas/Snow.tsx
front/src/components/SnowGlobeCanvas/SnowGlobeCanvas.tsx

- useFrame의 delta 사용하여 해결 
closed #41

[오승엽] useFrame 속도 다른문제 해결

---

back/package-lock.json
back/package.json
back/src/modules/auth/auth.controller.ts
back/src/modules/message/dto/create-message.dto.ts
back/src/modules/message/entity/message.entity.ts
back/src/modules/snowball/dto/decoration-snowball.dto.ts
back/src/modules/snowball/entity/snowball-decoration.entity.ts
back/src/modules/snowball/entity/snowball.entity.ts
back/src/modules/snowball/entity/user.entity.ts
package-lock.json

[송현우] erd 변경사항 적용

---

back/src/modules/auth/auth.controller.ts
back/src/modules/auth/auth.service.ts
back/src/modules/message/dto/request/req-create-message.dto.ts
back/src/modules/message/entity/message.entity.ts
back/src/modules/message/message.controller.ts
back/src/modules/message/message.service.ts
back/src/modules/snowball/dto/request/req-update-decoration.dto.ts
back/src/modules/snowball/dto/request/req-update-snowball.dto.ts
back/src/modules/snowball/dto/snowball.dto.ts
back/src/modules/snowball/snowball.service.ts

[송현우] message & auth swagger 완성

---

back/.dockerfile
back/Dockerfile

[최진수] : CI/CD 구성중

---

front/src/components/Msg/Msg.tsx
front/src/components/SnowGlobeCanvas/SnowGlobeCanvas.tsx
front/src/components/SnowGlobeCanvas/models/Deco.tsx
front/src/components/SnowGlobeCanvas/models/Raycaster.tsx
front/src/constants/deco.tsx
front/src/pages/Visit/MessageProvider.tsx
front/src/pages/Visit/Visit.tsx
front/src/pages/Visit/VisitButton.tsx

- useContext사용해서 해결했음
- 아직 /visit에서만 됨
</div>

[오승엽] 장식 클릭시 메시지 컴포넌트 출력

---

.github/workflows/BackEnd.yml
back/.dockerfile
back/Dockerfile
back/src/modules/message/message.controller.ts

[송현우] 강제 push 후 변경 사항 저장

---

.github/workflows/FrontEnd.yml
back/package-lock.json
back/package.json
back/src/main.ts
back/src/util/swagger.ts
back/tsconfig.json

[송현우] swagger 인증 구현

---

front/src/App.tsx
front/src/GlobalStyles.tsx
front/src/components/SnowGlobeCanvas/SnowGlobeCanvas.tsx
front/src/components/UIContainer/UIContainer.tsx
front/src/components/UIContainer/index.tsx
front/src/pages/Intro/Intro.tsx
front/src/pages/Intro/IntroButtonBox.tsx
front/src/pages/Intro/LoginBox.tsx

Fe/style/change UI

---

back/src/main.ts
back/src/modules/auth/auth.service.ts
back/src/modules/auth/dto/response/res-info.dto.ts
back/src/modules/auth/dto/user.dto.ts
back/src/modules/auth/entity/user.entity.ts
back/src/modules/auth/kakao-auth.strategy.ts
back/src/modules/message/message.module.ts
back/src/modules/message/message.service.ts
back/src/modules/snowball/entity/snowball.entity.ts
package-lock.json
package.json

[송현우] api 명세 수정 및 폴더 변경

---

back/package-lock.json
back/package.json
back/src/modules/auth/auth.controller.ts
back/src/modules/auth/auth.module.ts
back/src/modules/auth/auth.service.ts
back/src/modules/auth/dto/user.dto.ts
back/src/modules/auth/strategy/google-auth.strategy.ts
back/src/modules/auth/strategy/kakao-auth.strategy.ts
back/src/modules/auth/strategy/naver-auth.strategy.ts

[송현우] strategy 보완 & auth 서비스 로직 작성

---

back/src/modules/auth/auth.guard.ts
back/src/modules/auth/auth.module.ts
back/src/modules/auth/auth.service.ts
back/src/modules/message/dto/request/req-create-message.dto.ts
back/src/modules/message/message.controller.ts
back/src/modules/message/message.service.ts
back/src/modules/snowball/dto/request/req-update-decoration.dto.ts
back/src/modules/snowball/dto/request/req-update-snowball.dto.ts
back/src/modules/snowball/snowball.controller.ts
back/src/modules/snowball/snowball.service.ts

[최진수] : JWT Guard 

---

front/src/App.tsx
front/src/components/HeaderText/HeaderText.tsx
front/src/components/Msg/Msg.tsx
front/src/components/SnowGlobeCanvas/models/Raycaster.tsx
front/src/pages/Intro/Intro.tsx
front/src/pages/Visit/Deco/Deco.tsx
front/src/pages/Visit/Deco/DecoCanvas/DecoCanvas.tsx
front/src/pages/Visit/Deco/DecoCanvas/DecoModel.tsx
front/src/pages/Visit/Deco/DecoEnroll.tsx
front/src/pages/Visit/Deco/Steps.tsx

[김찬우] 메세지 글자수 표시 및 스노우볼 줌 아웃 기능 구현

---

front/src/components/Prev/Prev.tsx
front/src/components/Song/Song.tsx
front/src/pages/Main/ListMsg.tsx
front/src/pages/Main/Main.tsx
front/src/pages/Main/MainButtonBox.tsx
front/src/pages/Main/MenuModal.tsx
front/src/pages/Visit/Deco/Steps.tsx

- `npm run build` 에러❌
- 추가 생각할 요소🥹
- 스크린샷 버튼 시 버튼 애니메이션으로 없어지기 구현
- `theme.tsx` 안쓰는 요소 삭제
- `orbitControls` 카메라 포지션 조정 후 고정 문제
- `100vh` 모든 기기 적용
- `merge` 시 확인
- `HeaderText.tsx`에서 `fadeInUp1` `transform` 시 x값 `0`
- 진행 #89 
</div>

[서민아] UIContainer 적용

---

back/src/app.module.ts
back/src/main.ts
back/src/modules/auth/auth.module.ts
back/src/modules/auth/auth.service.ts
back/src/modules/auth/strategy/google-auth.strategy.ts
back/src/modules/auth/strategy/kakao-auth.strategy.ts
back/src/modules/auth/strategy/naver-auth.strategy.ts
back/src/util/swagger.ts

[송현우] api 라우트 및 redirect url 변경

---

front/src/GlobalStyles.tsx
front/src/components/Button/StepButton.tsx
front/src/components/HeaderText/HeaderText.tsx
front/src/components/Msg/Msg.tsx
front/src/pages/Visit/Deco/Steps.tsx

- msg 스크롤됨
- msg textarea 자동으로 height 변경
</div>

[오승엽] Steps.tsx css변경

---

.github/workflows/TestFrontNginx.yml

[최진수] : testing deployment to Nginx server

---

back/src/modules/auth/auth.guard.ts
back/src/modules/auth/auth.service.ts
back/src/modules/auth/dto/response/res-info.dto.ts
back/src/modules/auth/strategy/google-auth.strategy.ts
back/src/modules/auth/strategy/kakao-auth.strategy.ts
back/src/modules/auth/strategy/naver-auth.strategy.ts
back/src/modules/message/entity/letter.entity.ts
back/src/modules/message/entity/message.entity.ts
back/src/modules/snowball/entity/decoration-prefix.entity.ts
back/src/modules/snowball/entity/snowball-decoration.entity.ts
back/src/modules/snowball/snowball.service.ts

[송현우] 쿼리 최적화 및 서비스 로직

---

back/src/modules/auth/auth.guard.ts
back/src/modules/auth/auth.service.ts
back/src/modules/auth/dto/user.dto.ts
back/src/modules/auth/entity/user.entity.ts
back/src/modules/auth/strategy/google-auth.strategy.ts
back/src/modules/auth/strategy/kakao-auth.strategy.ts
back/src/modules/auth/strategy/naver-auth.strategy.ts
back/src/modules/message/entity/letter.entity.ts
back/src/modules/message/message.controller.ts
back/src/modules/snowball/entity/decoration-prefix.entity.ts
back/src/modules/snowball/entity/snowball.entity.ts
back/src/modules/snowball/snowball.controller.ts
back/src/util/swagger.ts

[송현우] 서비스 로직 완성

---

back/src/modules/message/message.controller.ts
back/src/modules/message/message.service.ts

user_id가 칼럼으로 추가되면서 생성이 안되는 문제 발생
두가지 해결책이 있었음
1. user_id를 param으로 받기
2. snowball_id로 해당하는 user_id를 find하기
1번으로 했다가 restful하지 않을 것 같아 2번으로 바꿈.. 추후에 논의 필요

[송현우] createMessage API 디버깅

---

front/package-lock.json
front/package.json
front/src/GlobalStyles.tsx
front/src/components/SnowGlobeCanvas/models/Snow.tsx
front/src/pages/Intro/Introduce.tsx
front/src/pages/Intro/LoginBox.tsx
front/vite.config.ts

[오승엽] 테스트용 pr입니다

---

front/src/pages/Intro/Introduce.tsx
front/src/pages/Intro/LoginBox.tsx

[FE] 로그인 확인용 a 태그

---

front/src/pages/Intro/Introduce.tsx

[FE] a태그 overflow 해결

---

back/src/modules/auth/auth.controller.ts
back/src/modules/message/entity/message.entity.ts
back/src/modules/snowball/entity/snowball.entity.ts
back/src/modules/user/entity/user.entity.ts

[송현우] access token 저장, todo 메모

---

front/src/pages/Make/Snowball/MainModel.tsx
front/src/pages/Make/Snowball/MainProvider.tsx
front/src/pages/Make/Snowball/MakeSnowballCanvas.tsx

- 현재 id랑 color만 상태관리 _(추후 필요한거 더 추가합시다❗)_
</div>

[서민아] main deco canvas

---

back/package-lock.json
back/package.json
back/src/main.ts
back/src/modules/auth/auth.controller.ts
back/src/modules/message/dto/message.dto.ts
back/src/modules/message/dto/request/req-create-message.dto.ts
back/src/modules/message/dto/response/res-create-message.dto.ts
back/src/modules/message/dto/update-message-decoration.dto.ts
back/src/modules/message/dto/update-message-location.dto.ts
back/src/modules/message/entity/message.entity.ts
back/src/modules/message/message.service.ts
back/src/modules/snowball/entity/snowball.entity.ts
back/src/modules/snowball/snowball.service.ts
back/src/modules/user/dto/nickname.dto.ts
back/src/modules/user/dto/user.dto.ts
back/src/modules/user/entity/user.entity.ts
back/src/modules/user/user.service.ts

[송현우] 파이프 등록, user/message 모듈 dto validation

---

back/src/modules/message/entity/message.entity.ts
back/src/modules/message/message.service.ts
back/src/modules/snowball/entity/snowball.entity.ts
back/src/modules/snowball/snowball.controller.ts

[송현우] 스노우볼 생성 및 조회 프론트 연동

---

front/src/App.tsx
front/src/components/Button/index.tsx
front/src/components/HeaderText/HeaderText.tsx
front/src/components/Msg/Msg.tsx
front/src/components/SnowGlobeCanvas/SnowGlobeCanvas.tsx
front/src/components/SnowGlobeCanvas/models/Deco.tsx
front/src/components/SnowGlobeCanvas/models/Snow.tsx
front/src/components/index.tsx
front/src/constants/deco.tsx
front/src/mockdata.json
front/src/pages/Main/ListMsg.tsx
front/src/pages/Main/MainButtonBox.tsx
front/src/pages/Main/MenuModal.tsx
front/src/pages/MainDeco/MsgBox.tsx
front/src/pages/MainDeco/Steps.tsx
front/src/pages/Make/Snowball/Snowball.tsx
front/src/pages/Visit/Deco/DecoBox.tsx
front/src/pages/Visit/Deco/DecoProvider.tsx
front/src/pages/Visit/Deco/MsgBox.tsx
front/src/pages/Visit/Deco/PostButton.tsx
front/src/pages/Visit/Deco/Steps.tsx
front/src/pages/Visit/SnowBallProvider.tsx
front/src/pages/Visit/Visit.tsx
front/src/pages/Visit/VisitBody.tsx
front/src/pages/Visit/VisitHeader.tsx

<h4>스노우볼데이터 불러오기</h4>
</div>
<h4>메시지 작성 POST API</h4>
</div>

[오승엽] visit페이지 api연동

---

front/src/App.tsx
front/src/router/IsLogin.tsx

[FE] router test

---

front/src/components/SnowGlobeCanvas/SnowGlobeCanvas.tsx
front/src/mockdata.json
front/src/pages/Visit/SnowBallProvider.tsx

[오승엽] 받침대 db적용

---

front/src/pages/Visit/SnowBallProvider.tsx
front/src/utils/position.tsx
front/vite.config.ts

- 분명 position 인덱스 바꿔놨는데 commit안되어있네

[오승엽] 메시지 30개일때 렌더링x 수정

---

front/package-lock.json
front/package.json
front/vite.config.ts

`npm install vite-plugin-mkcert` 해야합니다.

[김찬우] 로컬호스트 https 리퀘스트 오류 수정

---

back/src/modules/auth/auth.controller.ts

- 쿠키 지워주고 /로 리다이렉트
access_token이 있는걸 볼 수 있다.
로그아웃 요청보낸후 없어진걸 확인할 수 있다.
</div>

[최진수] : 로그아웃 api + 

---

front/src/App.tsx
front/src/components/Msg/ListMsg.tsx
front/src/components/Msg/Msg.tsx
front/src/components/Msg/index.tsx
front/src/components/SnowGlobeCanvas/SnowGlobeCanvas.tsx
front/src/components/index.tsx
front/src/pages/Main/ListMsg.tsx
front/src/pages/Main/ListMsgs.tsx
front/src/pages/Main/MainButtonBox.tsx
front/src/pages/Main/MenuModal.tsx
front/src/pages/Make/Snowball/MainDeco/DecoEnroll.tsx
front/src/router/IsLogin.tsx
front/src/router/IsSnowballData.tsx
front/src/router/index.tsx
front/vite.config.ts

[김찬우] 리스트 뷰 보기 구현, 라우터 수정, 공유하기, 메시지 삭제

---

front/src/pages/Visit/Deco/PostButton.tsx

[오승엽] 핫픽스!!!! 메시지작성 api url수정

---

front/src/pages/Visit/Deco/PostButton.tsx

[오승엽] 진짜 핫픽스!!! 메시지 api변동 진짜 고침

---

back/src/modules/message/message.service.ts

[송현우] pr 테스트

---

front/package-lock.json
front/src/components/Msg/Msg.tsx
front/src/pages/Main/Main.tsx

[김찬우] hotfix Visit 페이지 메세지 렌더링 오류 수정 및 메인 페이지 CSS 수정

---

front/src/App.tsx
front/src/utils/Loading.tsx

[김찬우] 로딩 페이지 및 GIF 추가

---

front/src/pages/Main/Main.tsx
front/src/pages/Main/MainButtonBox.tsx
front/src/pages/Make/Snowball/MainDeco/DecoEnroll.tsx
front/src/pages/Visit/Visit.tsx

[FE] 로딩페이지

---

front/index.html
front/src/components/Msg/Msg.tsx
front/src/pages/Intro/Introduce.tsx

`npm run build` error ❌
- 멘트 수정 완료
- 스크롤 허용 ➡️ `pointer-events: auto;`
- 아니 이거 이렇게 수정해서 메시지 길 때도 똑같이 스크롤 허용하려고 하는데,, 안돼서 너무 화나서 중도포기함🔥 우리 프론트는 천재만재들이니 분명 해결할 수 있을 것이라 믿음🙏ㅎㅎㅋㅋ
- 스노우볼 속 내마음
- 카카오 캐시 확인 필요💦
- default가 ''가 아니라 `익명`이네요~? 익명으로 바꿨습니당!
</div>

[서민아] 소개글 멘트 수정 및 스크롤 허용

---

front/index.html
front/src/App.tsx
front/src/components/Modal/Modal.tsx
front/src/components/Modal/index.tsx
front/src/components/Msg/ListMsg.tsx
front/src/components/Msg/Msg.tsx
front/src/components/SnowGlobeCanvas/Decos.tsx
front/src/components/SnowGlobeCanvas/SnowGlobeCanvas.tsx
front/src/components/SnowGlobeCanvas/models/Deco.tsx
front/src/components/SnowGlobeCanvas/models/Raycaster.tsx
front/src/components/index.tsx
front/src/mockdata.json
front/src/pages/Intro/LoginBox.tsx
front/src/pages/Main/ListMsgs.tsx
front/src/pages/Main/Main.tsx
front/src/pages/Main/MainBody.tsx
front/src/pages/Visit/Deco/DecoProvider.tsx
front/src/pages/Visit/Deco/PostButton.tsx
front/src/pages/Visit/MessageListProvider.tsx
front/src/pages/Visit/MessageProvider.tsx
front/src/pages/Visit/SnowBallProvider.tsx
front/src/pages/Visit/VisitBody.tsx
front/src/utils/theme.tsx

[김찬우, 오승엽, 서민아] 모달 생성, 읽은 메세지 구현, 각종 예외처리

---

front/src/pages/Make/Snowball/Snowball.tsx

[오승엽] 로그인 버그 핫픽스

---

front/package-lock.json
front/package.json
front/src/hooks/useLogout.tsx
front/src/pages/Intro/Intro.tsx
front/src/pages/Main/Main.tsx
front/src/pages/Main/MenuModal.tsx

- 자세한내용은 기술로그 참조
- https://delicious-halloumi-7ae.notion.site/CustomHook-cfd6c607f937460aa88a847e5a0822fe?pvs=4
❗배포하고 테스트 해봐야함~
<h3>오늘의 아놔 포인트</h3>
</div>

[오승엽] 빌드에러 수정, useLogout Hook 수정

---

front/src/hooks/useLogout.tsx

[FE] 로그아웃 redirect 수정

---

front/src/App.tsx
front/src/pages/Main/Main.tsx
front/src/pages/Main/MainButtonBox.tsx
front/src/pages/Main/MenuModal.tsx
front/src/pages/Visit/Deco/PostButton.tsx
package-lock.json
package.json

[김찬우] 토스트 메세지 추가

---

front/src/pages/Main/ListMsgs.tsx
front/src/pages/Main/LockModal.tsx
front/src/pages/Main/MainButtonBox.tsx
front/src/pages/Visit/SnowBallProvider.tsx

[김찬우] 비공개 공개 요청 모달 및 토스트 메세지 추가

---

front/src/GlobalStyles.tsx
front/src/components/Button/StepButton.tsx
front/src/components/Modal/Modal.tsx
front/src/pages/Main/ListMsgs.tsx
front/src/pages/Main/LockModal.tsx
front/src/pages/Main/MainButtonBox.tsx
front/src/pages/Make/Snowball/MainDeco/DecoEnroll.tsx
front/src/pages/Make/Snowball/Snowball.tsx
front/src/pages/Visit/Deco/Deco.tsx
front/src/pages/Visit/Deco/MsgBox.tsx
front/src/pages/Visit/SnowBallProvider.tsx
front/src/utils/theme.tsx

- `npm run build` error ❌
- 토스트모달 너비 조정 또 어디해야해요~?
- 자물쇠 이미지에 애니메이션 거는거 맞죠?
- 폰트나 다른거 암것도 안건드리고 너비만 80%로 지정했어요~ 가운데 줄맞춤 하구요! 다른거 수정하려면 하셔도 됩니당👍 기타 다른 토스트도 너비 조정 필요한 부분 있으면 알려주세요❗
</div>

[서민아] msg 및 토스트 모달 css 수정, 자물쇠 애니메이션

---

front/src/components/Modal/Modal.tsx
front/src/components/Msg/ListMsg.tsx
front/src/pages/Main/ListMsgs.tsx
front/src/pages/Main/Main.tsx
front/src/pages/Main/MainButtonBox.tsx
front/src/pages/Main/MenuModal.tsx
front/src/pages/Make/Snowball/MainDeco/Steps.tsx
front/src/pages/Visit/Deco/Steps.tsx

- API 요청을 새로 날리지 않고 클라이언트 단에서 지운값에 해당하는 메세지를 지웠습니다.

[김찬우] 메세지 리스트 delete 후 메세지 리렌더링 구현

---

.github/workflows/TestFrontNginx.yml
front/package-lock.json
front/package.json
front/src/App.tsx
front/src/components/Modal/Modal.tsx
front/src/index.tsx
front/src/pages/Main/ListMsgs.tsx
front/src/pages/Main/Main.tsx
front/src/pages/Main/MainBody.tsx
front/src/pages/Make/Nickname/Nickname.tsx
front/src/pages/Make/Snowball/MainDeco/DecoEnroll.tsx
front/src/pages/Make/Snowball/MainDeco/MakeButton.tsx
front/src/pages/Make/Snowball/Snowball.tsx
front/src/pages/Visit/Deco/PostButton.tsx
front/src/pages/Visit/SnowBallProvider.tsx
front/src/pages/Visit/Visit.tsx
front/src/pages/Visit/VisitBody.tsx
front/src/router/HasSnowballData.tsx
front/src/utils/axios.tsx

- 자세한 내용은 기술로그 참조 [🧾 Sentry 셋업!!](https://delicious-halloumi-7ae.notion.site/Sentry-8ec71828e178447bbfffed6c6a5fa87b?pvs=4)
</div>

[오승엽] Sentry 셋업

---

front/src/pages/Main/Main.tsx
front/src/pages/Main/MainBody.tsx

- 한 계정으로 여러명이 동시접속 하는거 아니면 문제 없을듯
<h3>수정 전 읽은 메시지장식 클릭시 409받음</h3>
</div>
<h3>처리 완료</h3>
</div>

[오승엽] 메시지 읽음처리 수정, 스노우볼 이동 버튼 수정

---

front/index.html
front/src/components/Modal/Modal.tsx
front/src/pages/Main/LockModal.tsx
front/src/pages/Main/MainButtonBox.tsx
front/src/pages/Visit/SnowBallProvider.tsx

[김찬우] 잠금기능 핫픽스 및 크롱님 피드백 적용

---

front/src/components/SnowGlobeCanvas/Decos.tsx
front/src/pages/Main/Main.tsx
front/src/pages/Make/Snowball/MainDeco/Steps.tsx
front/src/pages/Visit/Deco/Steps.tsx
front/src/pages/Visit/Visit.tsx
front/src/pages/Visit/VisitBody.tsx

[김찬우] 좌우 애로우 클릭 이후 비공개 메시지가 읽히는 오류 수정

---

front/src/pages/Visit/VisitHeader.tsx

[오승엽] visit페이지에 홈으로 가는 버튼 추가

---

front/src/App.tsx
front/src/pages/Main/Main.tsx
front/src/router/HasSnowballData.tsx

[김찬우] 라우터 분리

---

front/src/App.tsx
front/src/pages/Main/Main.tsx
front/src/pages/Main/MenuModal.tsx
front/src/pages/Make/Snowball/Snowball.tsx
front/src/router/HasSnowballData.tsx

[김찬우] 토스트 메세지 타이머 수정 및 라우팅 에러처리 수정

---

front/src/pages/Main/MainButtonBox.tsx

[오승엽] 핫픽스! 전체화면 취소시 <>버튼 안생김

---

back/k6-test/average_load_test.js
back/k6-test/soak_test.js
back/k6-test/spike_test.js
back/k6-test/test-gradual-visit.js
back/k6-test/test.js
back/k6-test/testConstantVU.js

집 네트워크가 좀 불안정해서 재실행 하면 결과가 다를듯하다.
AVERAGE LOAD TEST
SPIKE TEST
</div>

[최진수] : 테스트 추가

---

front/src/App.tsx
front/src/pages/Main/Main.tsx
front/src/pages/Make/Nickname/Nickname.tsx
front/src/pages/Make/Snowball/Snowball.tsx
front/src/router/HasSnowballData.tsx

[김찬우] 라우터 예외처리 수정

---

front/src/App.tsx

아직 사용하는 코드를 세분화 하여 나누지 못해 `npm run build` 시 생성되는 JS 소스파일들이 크게 나누어지지는 않고 있습니다.
기존 컴포넌트의 재사용성을 높여 코드를 더욱 더 세분하게 분할한다면 더 좋은 향상을 볼수 있을것입니다.
React 의 `lazy` `suspense` 방식을 이용해 Network 탭의 로드 되는 시간을 기존 평균 450ms 속도에서 380ms 로 대략 `20%` 가량 로딩 시간을 개선시켰습니다.
기존의 network 탭에서 사용하지 않는 tsx 파일들을 로드되는것을 볼수 있는데, 개선 후 사용되지 않는 파일들은 로드가 되지 않는것을 확인 할 수 있습니다.
Lighthouse 의 경우 대략 `25%` 의 성능 향상을 보였지만, `SI` `FCP` `LCP` 등 여전히 성능 개선해야할 필요가 있습니다.
<table align="center" width="100%">
<th width="20%">코드 스플리팅 전</th>
<th width="20%">코드 스플리팅 후</th>
<tr>
<td><img src="https://github.com/boostcampwm2023/web11-SSOCK/assets/98443541/7764b33e-8e91-4c4f-b658-155c3e5abf9a" width="500"/></td>
<td><img src="https://github.com/boostcampwm2023/web11-SSOCK/assets/98443541/1672c8cf-d16a-4da5-9d16-dbba8cd17f13" width="500"/></td>
</tr>
<tr> …

[김찬우] 코드스플리팅 적용
